import { useState } from 'react';
import QRCode from 'qrcode';
import { useDatabase } from '../context/DatabaseContext';
import PhotoCapture from './PhotoCapture';
import SignatureCapture from './SignatureCapture';
import IdCard from './IdCard';
import { 
  UserPlus, 
  Save, 
  X, 
  AlertCircle, 
  Info 
} from 'lucide-react';
import confetti from 'canvas-confetti';

export default function StaffRegistrationForm({ editingStaff = null, onCompleted }) {
  const { addStaff, updateStaff, designations, addDesignation, schoolSettings } = useDatabase();

  const isTeachingDesignation = (designation = '') => /teacher|head|director|principal/.test(designation.toLowerCase());

  const [form, setForm] = useState(() => ({
    staff_number: editingStaff?.staff_number || '',
    full_name: editingStaff?.full_name || '',
    gender: editingStaff?.gender || 'Male',
    department: editingStaff?.department || 'Science',
    designation: editingStaff?.designation || '',
    subjects: isTeachingDesignation(editingStaff?.designation) ? editingStaff?.subjects || '' : '',
    status: editingStaff?.status || 'Active',
    issue_date: editingStaff?.issue_date || '',
    expiry_date: editingStaff?.expiry_date || ''
  }));

  const [photoUrl, setPhotoUrl] = useState(() => editingStaff?.photo_url || '');
  const [signatureUrl, setSignatureUrl] = useState(() => editingStaff?.signature_url || '');
  
  // Card Preview controls
  const [cardSide, setCardSide] = useState('front');
  const [errorMessage, setErrorMessage] = useState('');
  const [saving, setSaving] = useState(false);
  const [successMessage, setSuccessMessage] = useState('');

  // Date controls
  const [autoGenerateDates, setAutoGenerateDates] = useState(false);

  const handleAutoGenerateToggle = (checked) => {
    setAutoGenerateDates(checked);
    if (checked) {
      const today = new Date().toISOString().split('T')[0];
      const expiry = new Date();
      expiry.setFullYear(expiry.getFullYear() + 5);
      const expiryStr = expiry.toISOString().split('T')[0];
      
      setForm(prev => ({
        ...prev,
        issue_date: today,
        expiry_date: expiryStr
      }));
    } else {
      setForm(prev => ({
        ...prev,
        issue_date: '',
        expiry_date: ''
      }));
    }
  };

  // Add new designation controls
  const [showNewDesignationInput, setShowNewDesignationInput] = useState(false);
  const [newDesignationName, setNewDesignationName] = useState('');

  const handleAddNewDesignation = async () => {
    if (!newDesignationName.trim()) return;
    try {
      const newD = await addDesignation(newDesignationName.trim());
      setForm(prev => ({ ...prev, designation: newD.name }));
      setShowNewDesignationInput(false);
      setNewDesignationName('');
    } catch (err) {
      alert(err.message || "Failed to add designation.");
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm(prev => {
      if (name === 'designation') {
        const normalized = value.toLowerCase();
        const isTeaching = /teacher|head|director|principal/.test(normalized);
        return {
          ...prev,
          designation: value,
          subjects: isTeaching ? prev.subjects : ''
        };
      }
      return {
        ...prev,
        [name]: value
      };
    });
  };

  const handlePhotoProcessed = (dataUrl) => {
    setPhotoUrl(dataUrl);
  };

  const handleSignatureProcessed = (dataUrl) => {
    setSignatureUrl(dataUrl);
  };

  const getComputedCardNumber = () => {
    const value = form.staff_number?.trim();
    if (!value) return 'STP-XXXXXX-0';
    return value.replace(/\//g, '-').replace(/\s+/g, '-').toUpperCase();
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setErrorMessage('');
    setSuccessMessage('');
    
    // Basic validations
    if (!form.staff_number.trim()) {
      setErrorMessage('Staff Number is required.');
      return;
    }
    if (!form.full_name.trim()) {
      setErrorMessage('Full Name is required.');
      return;
    }

    setSaving(true);
    try {
      const dataToSave = {
        ...form,
        photo_url: photoUrl,
        signature_url: signatureUrl
      };

      if (editingStaff) {
        await updateStaff(editingStaff.id, dataToSave);
      } else {
        await addStaff(dataToSave);
        // Success confetti for new registrations!
        confetti({
          particleCount: 80,
          spread: 60,
          origin: { y: 0.7 }
        });
      }

      // Show success message briefly before closing form
      setSuccessMessage('Staff record saved successfully');
      setTimeout(() => {
        onCompleted();
      }, 900);
    } catch (err) {
      setErrorMessage(err.message || 'An error occurred while saving staff details.');
    } finally {
      setSaving(false);
    }
  };

  // Preview object for the live card preview
  const livePreviewStaff = {
    ...form,
    photo_url: photoUrl,
    signature_url: signatureUrl,
    card_number: editingStaff ? editingStaff.card_number : getComputedCardNumber()
  };

  const [qrActionMsg, setQrActionMsg] = useState('');

  const DEFAULT_VERIFICATION_BASE_URL = import.meta.env.VITE_VERIFICATION_BASE_URL || 'https://my-public-domain.com';

  const getVerifyBaseUrl = () => {
    if (schoolSettings?.verification_base_url) return schoolSettings.verification_base_url.replace(/\/$/, '');
    return DEFAULT_VERIFICATION_BASE_URL.replace(/\/$/, '');
  };

  const verificationUrl = `${getVerifyBaseUrl()}/verify/${encodeURIComponent(livePreviewStaff.card_number)}`;

  const handleCopyVerifyUrl = async () => {
    try {
      await navigator.clipboard.writeText(verificationUrl);
      setQrActionMsg('Verification URL copied to clipboard');
      setTimeout(() => setQrActionMsg(''), 2000);
    } catch (err) {
      setQrActionMsg('Unable to copy URL');
      setTimeout(() => setQrActionMsg(''), 2000);
    }
  };

  const handleDownloadQr = async () => {
    try {
      const dataUrl = await QRCode.toDataURL(verificationUrl, { width: 600, margin: 2 });
      const a = document.createElement('a');
      a.href = dataUrl;
      a.download = `${livePreviewStaff.card_number || 'verification'}.png`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      setQrActionMsg('QR downloaded');
      setTimeout(() => setQrActionMsg(''), 2000);
    } catch (err) {
      console.error('QR download failed', err);
      setQrActionMsg('Failed to generate QR');
      setTimeout(() => setQrActionMsg(''), 2000);
    }
  };

  const departments = [
    'Science',
    'Humanities',
    'Mathematics',
    'Languages',
    'Vocational',
    'Administration',
    'Support Staff',
    'Security'
  ];

  const activeDesignations = designations.filter(d => d.status === 'Active' || d.name === form.designation);

  const isTeachingStaff = /teacher|head|director|principal/.test(form.designation.toLowerCase());

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between border-b border-slate-800 pb-4">
        <h2 className="text-xl font-bold text-slate-100 flex items-center gap-2 font-outfit">
          <UserPlus className="h-5 w-5 text-sky-400" />
          {editingStaff ? `Edit Staff Member: ${editingStaff.full_name}` : 'Register New Staff'}
        </h2>
        <button
          type="button"
          onClick={onCompleted}
          className="p-2 text-slate-400 hover:text-slate-200 hover:bg-slate-800 rounded-xl transition"
        >
          <X className="h-5 w-5" />
        </button>
      </div>

      {errorMessage && (
        <div className="p-4 bg-rose-500/10 border border-rose-500/20 text-rose-400 rounded-xl flex items-start gap-3">
          <AlertCircle className="h-5 w-5 flex-shrink-0 mt-0.5" />
          <div className="text-xs font-semibold">{errorMessage}</div>
        </div>
      )}
      {successMessage && (
        <div className="p-4 bg-emerald-500/10 border border-emerald-500/20 text-emerald-300 rounded-xl flex items-start gap-3">
          <Info className="h-5 w-5 flex-shrink-0 mt-0.5 text-emerald-400" />
          <div className="text-xs font-semibold">{successMessage}</div>
        </div>
      )}

      <form onSubmit={handleSubmit} className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Hand: Registration Form Fields */}
        <div className="lg:col-span-5 space-y-4 bg-slate-800/40 p-5 rounded-2xl border border-slate-800">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest border-b border-slate-800 pb-2 mb-2">
            Staff Particulars
          </h3>
          
          <div>
            <label className="block text-xs font-semibold text-slate-400 mb-1.5">Staff Number *</label>
            <input
              type="text"
              name="staff_number"
              value={form.staff_number}
              onChange={handleChange}
              placeholder="e.g. STP/2026/001"
              className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-sky-500"
              required
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-400 mb-1.5">Card Verification Token</label>
            <input
              type="text"
              value={getComputedCardNumber()}
              readOnly
              className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-xs text-slate-300 cursor-not-allowed"
            />
            <p className="text-[10px] text-slate-500 mt-1">This token is used for QR verification links and protects the staff ID card.</p>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-400 mb-1.5">Full Name *</label>
            <input
              type="text"
              name="full_name"
              value={form.full_name}
              onChange={handleChange}
              placeholder="e.g. Kibuuka Richard"
              className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-sky-500"
              required
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-slate-400 mb-1.5">Gender</label>
              <select
                name="gender"
                value={form.gender}
                onChange={handleChange}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-sky-500"
              >
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Other">Other</option>
              </select>
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-400 mb-1.5">Department</label>
              <select
                name="department"
                value={form.department}
                onChange={handleChange}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-sky-500"
              >
                {departments.map(d => (
                  <option key={d} value={d}>{d}</option>
                ))}
              </select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <div className="flex justify-between items-center mb-1.5">
                <label className="block text-xs font-semibold text-slate-400">Designation *</label>
                {!showNewDesignationInput && (
                  <button
                    type="button"
                    onClick={() => setShowNewDesignationInput(true)}
                    className="text-[10px] text-sky-400 hover:text-sky-300 font-bold"
                  >
                    [ + Add New ]
                  </button>
                )}
              </div>
              
              {showNewDesignationInput ? (
                <div className="flex gap-1.5">
                  <input
                    type="text"
                    placeholder="Enter designation..."
                    value={newDesignationName}
                    onChange={(e) => setNewDesignationName(e.target.value)}
                    className="flex-1 bg-slate-900 border border-slate-700 rounded-xl px-3 py-1.5 text-xs text-white focus:outline-none focus:border-sky-500 font-semibold"
                  />
                  <button
                    type="button"
                    onClick={handleAddNewDesignation}
                    className="px-3 bg-sky-600 hover:bg-sky-500 text-white rounded-xl text-[10px] font-bold"
                  >
                    Save
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setShowNewDesignationInput(false);
                      setNewDesignationName('');
                    }}
                    className="px-2.5 bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-slate-200 rounded-xl text-[10px] font-semibold"
                  >
                    Cancel
                  </button>
                </div>
              ) : (
                <select
                  name="designation"
                  value={form.designation}
                  onChange={handleChange}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-sky-500 font-semibold"
                  required
                >
                  <option value="" disabled>Select Designation</option>
                  {activeDesignations.map(d => (
                    <option key={d.id} value={d.name}>{d.name}</option>
                  ))}
                </select>
              )}
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-400 mb-1.5">Status</label>
              <select
                name="status"
                value={form.status}
                onChange={handleChange}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-sky-500"
              >
                <option value="Active">Active</option>
                <option value="Inactive">Inactive</option>
              </select>
            </div>
          </div>

          <div className="border-t border-slate-800 pt-3 mt-3 space-y-3">
            <div className="flex items-center justify-between">
              <label className="text-xs font-bold text-slate-400 uppercase tracking-wider">Card Dates</label>
              <label className="flex items-center gap-1.5 text-[10px] text-sky-400 font-bold cursor-pointer">
                <input
                  type="checkbox"
                  checked={autoGenerateDates}
                  onChange={(e) => handleAutoGenerateToggle(e.target.checked)}
                  className="rounded border-slate-700 bg-slate-900 text-sky-500 focus:ring-0 focus:ring-offset-0 h-3 w-3"
                />
                Auto-generate (Today & +5 Years)
              </label>
            </div>
            
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-semibold text-slate-400 mb-1.5">Issue Date</label>
                <input
                  type="date"
                  name="issue_date"
                  value={form.issue_date}
                  onChange={handleChange}
                  disabled={autoGenerateDates}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-sky-500 disabled:opacity-50"
                />
              </div>
              <div>
                <label className="block text-xs font-semibold text-slate-400 mb-1.5">Expiry Date</label>
                <input
                  type="date"
                  name="expiry_date"
                  value={form.expiry_date}
                  onChange={handleChange}
                  disabled={autoGenerateDates}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-sky-500 disabled:opacity-50"
                />
              </div>
            </div>
          </div>

          {/* Subjects: Teaching staff only */}
          {isTeachingStaff && (
            <div>
              <label className="block text-xs font-semibold text-slate-400 mb-1.5">Subjects Taught (comma separated)</label>
              <input
                type="text"
                name="subjects"
                value={form.subjects}
                onChange={handleChange}
                placeholder="e.g. Physics, Mathematics"
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-sky-500"
              />
              <p className="text-[10px] text-slate-500 mt-1 flex items-center gap-1">
                <Info className="h-3 w-3" /> Visible only for teaching staff designations
              </p>
            </div>
          )}
        </div>

        {/* Middle Columns: Media Captures (Photo & Signature) */}
        <div className="lg:col-span-4 space-y-4">
          <PhotoCapture 
            photoUrl={photoUrl} 
            onPhotoProcessed={handlePhotoProcessed} 
          />
          <SignatureCapture 
            signatureUrl={signatureUrl} 
            onSignatureProcessed={handleSignatureProcessed} 
            label="Holder Signature"
          />
        </div>

        {/* Right Columns: Live Card Preview & Action buttons */}
        <div className="lg:col-span-3 flex flex-col justify-between space-y-6">
          <div className="space-y-4">
            <div className="flex justify-between items-center">
              <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest">
                Live Card Preview
              </h3>
              <div className="flex bg-slate-800 rounded-lg p-0.5 border border-slate-700">
                <button
                  type="button"
                  onClick={() => setCardSide('front')}
                  className={`px-2 py-1 text-[10px] font-bold rounded-md transition ${
                    cardSide === 'front' ? 'bg-sky-600 text-white' : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  Front
                </button>
                <button
                  type="button"
                  onClick={() => setCardSide('back')}
                  className={`px-2 py-1 text-[10px] font-bold rounded-md transition ${
                    cardSide === 'back' ? 'bg-sky-600 text-white' : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  Back
                </button>
              </div>
            </div>

            {/* Container to scale card rendering for this column */}
            <div className="flex justify-center bg-slate-950/40 p-4 rounded-2xl border border-slate-800 relative overflow-x-auto">
              <div className="scale-75 origin-center -my-8">
                <IdCard 
                  staff={livePreviewStaff} 
                  side={cardSide} 
                  width={380} 
                  isDesignerMode={false} 
                />
              </div>
            </div>
              {/* QR quick actions for testing */}
              <div className="mt-2 flex items-center justify-center gap-2">
                <button
                  type="button"
                  onClick={handleCopyVerifyUrl}
                  className="px-3 py-1 text-xs bg-slate-800 hover:bg-slate-700 rounded-md text-slate-200 border border-slate-700"
                >
                  Copy Verification URL
                </button>
                <button
                  type="button"
                  onClick={handleDownloadQr}
                  className="px-3 py-1 text-xs bg-sky-600 hover:bg-sky-500 rounded-md text-white"
                >
                  Download QR (PNG)
                </button>
              </div>
              {qrActionMsg && (
                <div className="text-[11px] text-slate-400 text-center mt-1">{qrActionMsg}</div>
              )}
            
            <div className="text-[10px] text-slate-500 leading-relaxed text-center px-4 bg-slate-800/20 py-2 rounded-xl border border-slate-800/40">
              Card preview updates in real time. Standard layout scales automatically to PVC printer sizes when printing.
            </div>
          </div>

          <div className="space-y-3 pt-6 border-t border-slate-800">
            <button
              type="submit"
              disabled={saving}
              className={`w-full py-3 px-4 bg-sky-600 hover:bg-sky-500 text-white rounded-xl font-bold flex items-center justify-center gap-2 shadow-lg shadow-sky-950/50 transition-all ${
                saving ? 'opacity-50 cursor-not-allowed' : ''
              }`}
            >
              <Save className="h-4.5 w-4.5" />
              {saving ? 'Saving...' : editingStaff ? 'Save Changes' : 'Register & Save Staff'}
            </button>
            <button
              type="button"
              onClick={onCompleted}
              className="w-full py-2.5 px-4 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl text-xs font-semibold transition"
            >
              Cancel
            </button>
          </div>

        </div>

      </form>
    </div>
  );
}
